print("Welcome to eMobilis Technology Mobile Academy")
print('My first day within the academy was extraordinary')
print("On the same day I was welcomed by an oriantation from Mr.Erick")
print(38-23)
print("76*19")
print("My day was amazing as I saw different and wonderful people from all walks of life")
print(54/6)
print("94*0")
print(94-97)
print("My life in high school was quite Intresting")
print("My parents are happy with my achievements")
print(98-54)
print("67*76")